common/models/OrderProduct.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "order".
 *
 */
class OrderProduct extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'order_product';
    }

    /**
     * @inheritdoc
     */
    public function rules() { 
        return [
            [['orderId', 'productId', 'productData', 'name', 'quantity', 'price'], 'required'],
            [['name'], 'string', 'max' => 255],
        ];
    }

					
    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'customerId' => 'Mã khách hàng',
            'contactName' => 'Tên liên hệ',
            'contactPhone' => 'Số điện thoại liên hệ',
            'contactEmail' => 'Email liên hệ',
            'address' => 'Địa chỉ nhận hàng',
            'note' => 'Ghi chú',
            'confirmTime' => 'Thời gian xác nhận',
            'doneTime' => 'Thời gian hoàn thành',
            'cancelTime' => 'Thời gian hủy',
            'status' => 'Trạng thái',
        ];
    }

    public function getRating() {
        return $this->hasOne(Rating::className(), ['orderId' => 'orderId', 'productId' => 'productId']);
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\components\ImageClient;
use common\components\TextUtils;
use common\models\Etc;
use common\models\Homebox;
use common\models\Alias;
use common\models\Import;
use common\models\Keyword;
use common\models\Banner;
use common\models\Product;
use common\models\ProductImage;
use common\models\HotProduct;
use common\models\Subscriber;
use common\models\Merchant;
use common\models\CategorySuggest;
use common\models\MerchantHighlight;
use common\models\Smbox;
use frontend\components\Controller;
use common\components\VerifyEmail;
use Yii;
use yii\helpers\Url;
use common\models\Area;
use app\models\Homeboxv2;
use common\models\Category;
use yii\db\Expression;
use common\models\BoxPromotion;


class SiteController extends Controller
{
	public function actionIndex(){

		$this->view->title = 'Zoshop - ngon vô địch - rẻ vô địch - nhanh vô địch';
		$products = Product::find()->andWhere(['status' => 0])->orderBy('id desc')->limit(18)->all();
		$boxs = BoxPromotion::find()->andWhere(['status' => 1])->with(['product'])->orderBy('position')->all();

		return $this->render('index',
			[
				'products' => $products,
				'boxs' => $boxs,
			]
		);
	}

	public function actionUpload(){
		Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		header("Access-Control-Allow-Origin: *");
		// header("Access-Control-Allow-Credentials: true");
		if(!empty($_FILES['file'])){

			$allowedTypes = array(IMAGETYPE_PNG, IMAGETYPE_JPEG, IMAGETYPE_GIF);
			$detectedType = exif_imagetype($_FILES['file']['tmp_name']);
			if(!in_array($detectedType, $allowedTypes)){
				return ['success' => false, 'message' => 'Tệp tin tải lên phải là hình ảnh!'];
			}

			$file = $_FILES['file'];
			$duoi = explode('.', $file['name']);
			$duoi = end($duoi);
			$datetime = date('YmdHis');
			$path = 'assets/uploads/'.$datetime.'.jpg';
			move_uploaded_file($_FILES['file']['tmp_name'],$path);
			return ['success'=>true,'data'=>$path];
		}
	}

	 public function actionKeyword($keyword = null)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if ($keyword != null) {
            $keyword = strtolower($keyword);
            $alias = TextUtils::createAlias($keyword);
            $key = Keyword::findOne(['alias' => $alias]);
            if ($key == null) {
                $key = new Keyword();
                $key->alias = $alias;
                $key->keyword = TextUtils::createKeyword($keyword);
                $key->originKeyword = $keyword;
                $key->firstHit = microtime(true);
            }
            $key->hit++;
            $key->lastHit = microtime(true);
            $key->hps = $key->hit / ($key->lastHit - $key->firstHit);
            $key->save();
        }

        return true;
    }

    public function actionVerifyEmail($email = ''){
    	Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    	$vmail = new VerifyEmail();
    	return $vmail->echeck($email);
    }
}

frontend/views/site/error.php
<?php
use yii\helpers\Url;

?>

<div class="container container-v2">
  <div class="l-content">
    <ol class="breadcrumb">
      <li><a href="#">Trang chủ</a></li>
      <li class="active">404</li>
    </ol>
    <div class="c-whitebox">
      <div class="c-whitebox__inner">
        <div class="c-error">
          <div class="row">
            <div class="col-md-6">
              <div class="c-error__img"><img src="<?= Url::base() ?>/static/images/404.jpg" alt="404" /></div>
            </div><!-- col -->
            <div class="col-md-6">
              <div class="c-error__content">
                <div class="c-error__title">Không tồn tại</div>
                <div class="b-maincontent">
                  Nội dung bạn tìm kiếm không tồn tại hoặc đã bị xóa khỏi website
                  <br />Xin vui lòng liên hệ tới <b class="text-danger">1900 989 888</b> để được hỗ trợ miễn phí
                </div>
                <ul>
                  <li><a href="<?= Url::home() ?>"><i class="fa fa-home"></i><span>Trang chủ</span></a></li>
                  <li><a href="#"><i class="fa fa-phone"></i><span>Liên hệ</span></a></li>
                </ul>
              </div>
            </div><!-- col -->
          </div><!-- row -->
        </div><!-- c-error -->
      </div><!-- c-whitebox__inner -->
    </div><!-- c-whitebox -->
  </div><!-- l-content -->
</div><!-- container -->

frontend/views/site/index.php
<?php

use common\components\ImageClient;
use yii\helpers\Url;
use frontend\widgets\HomeProduct;
use frontend\widgets\ProductWidget;
use common\models\Area;
use common\models\Category;
use common\models\Urls;
use common\models\Banner;
use common\components\TextUtils;

$banner = Banner::find()->all();
?>

<div class="l-banner">
  <div class="container container-v2">
    <div class="l-banner-box">
      <div class="row">
        <div class="col-sm-3 l-banner-box__left">
          <a href="<?= $banner[0]->url ?>"><img src="<?= $banner[0]->image ?>"></a>
        </div>
        <div class="col-sm-6 l-banner-box__center">
          <div class="col-sm-12">
            <a href="<?= $banner[1]->image ?>"><img src="<?= $banner[1]->image ?>"></a>
          </div>
          <div class="l-banner-box__center__row">
            <div class="col-sm-6">
              <a href="<?= $banner[3]->image ?>"><img src="<?= $banner[3]->image ?>"></a>
            </div>
            <div class="col-sm-6">
              <a href="<?= $banner[4]->image ?>"><img src="<?= $banner[4]->image ?>"></a>
            </div>
          </div>
        </div>
        <div class="col-sm-3 l-banner-box__right">
          <a href="<?= $banner[2]->image ?>"><img src="<?= $banner[2]->image ?>"></a>
        </div>
      </div>
    </div><!-- l-banner-box -->
  </div><!-- container -->
</div><!-- l-banner -->
<div class="c-commit-block">
  <div class="container container-v2">
    <div class="c-commit-box is-3-col">
      <div class="c-commit-box__item">
        <div class="c-commit-box__item__inner">
          <div class="c-commit-box__item__inner__img">
            <img src="static/images/v2/icon-commit-1.png">
          </div>
          <div class="c-commit-box__item__inner__content">
            <h2>NGON VÔ ĐỊCH</h2>
            <p>Độ ngon thách thức người khó tính nhất</p>
          </div>
        </div>
      </div><!-- c-commit-box__item -->
      <div class="c-commit-box__item">
        <div class="c-commit-box__item__inner">
          <div class="c-commit-box__item__inner__img">
            <img src="static/images/v2/icon-commit-2.png">
          </div>
          <div class="c-commit-box__item__inner__content">
            <h2>RẺ VÔ ĐỊCH</h2>
            <p>Đồ ăn có mức giá rất rẻ</p>
          </div>
        </div>
      </div><!-- c-commit-box__item -->
      <div class="c-commit-box__item">
        <div class="c-commit-box__item__inner">
          <div class="c-commit-box__item__inner__img">
            <img src="static/images/v2/icon-commit-3.png">
          </div>
          <div class="c-commit-box__item__inner__content">
            <h2>NHANH VÔ ĐỊCH</h2>
            <p>Đội ngũ giao hàng siêu nhanh</p>
          </div>
        </div>
      </div><!-- c-commit-box__item -->
    </div><!-- c-commit-box -->
  </div><!-- container -->
</div><!-- c-commit-block -->
<div class="container container-v2">
  <div class="c-box">
    <div class="c-box__title"><h2 class="c-box__title__name">Khuyến mại hấp dẫn</h2></div>
    <div class="c-box__content">
      <div class="c-template-slider is-sale">
        <div class="owl-carousel" id="slide-countdown-0">
          <?php foreach ($boxs as $box): ?>
            <div class="c-product-square">
              <div class="c-product-square__shadow">
                <div class="c-product-square__thumb">
                  <div class="c-tag-countdown"><?= date("M d, Y h:i:s", $box->endTime); ?></div>
                  <a href="<?= $box->product->createUrl() ?>">
                    <img src="/<?= $box->product->image ?>" alt="image" />
                  </a>
                </div>
                <div class="c-product-square__content">
                  <div class="c-product-square__row">
                    <a class="c-product-square__title" href="<?= $box->product->createUrl() ?>"><?= $box->product->name ?></a>
                  </div>
                  <div class="c-product-square__row">
                    <span class="c-product-square__price"><?= number_format($box->product->price) ?><sup>đ</sup></span>
                    <?php if($box->product->promotion > $box->product->price){ ?>
                    <span class="c-product-square__oldprice"><?= number_format($box->product->promotion) ?><sup>đ</sup></span>
                    <?php } ?>
                  </div>
                  <div class="c-product-square__row">
                    <span class="c-star is-<?= $box->product->rating ?>">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                    </span>
                    <span class="c-product-square__view"><i class="fa fa-eye"></i><?= $box->product->view ?></span>
                  </div>
                  <div class="c-product-square__btn"><a href="<?= $box->product->createUrl() ?>">Mua ngay</a></div>
                </div>
              </div>
            </div>
          <?php endforeach ?>
          

        </div><!-- owl-carousel -->
      </div><!-- c-template-slider -->
    </div><!-- c-box__content -->
  </div><!-- c-box -->
  <div class="c-box">
    <div class="c-box__title"><h2 class="c-box__title__name">Menu Gọi món</h2></div>
    <div class="c-box__content">
      <div class="c-tabs clearfix">
        <div class="c-tabs__content">
          <div class="c-loading-gif" style="display: none;"></div>
          <div class="c-tabs__pane active" id="sach-tab-1" role="tabpanel">
            <div class="c-home-box is-big">
              <div class="c-home-product c-product-hover">
                <ul class="clearfix">
                  <?php foreach ($products as $product) { ?>
                  <li>
                    <div class="c-product-square">
                      <div class="c-product-square__shadow">
                        <div class="c-product-square__thumb">
                          <?php if($product->promotion && $product->promotion > $product->price){ 
                            $percent = floor(100-($product->price/$product->promotion*100));
                            ?>
                            <span class="c-tag-sale"><b>Giảm</b><?=$percent?>%</span>
                            <?php } ?>
                          <a href="<?= $product->createUrl() ?>"><img src="/<?= $product->image ?>" alt="image" /></a>
                        </div>
                        <div class="c-product-square__content">
                          <div class="c-product-square__row">
                            <a class="c-product-square__title" href="<?= $product->createUrl() ?>"><span class="icon-mall"></span><?= $product->name ?></a>
                          </div>
                          <div class="c-product-square__row">
                            <span class="c-product-square__price"><?= number_format($product->price) ?><sup>đ</sup></span>
                            <?php if($product->promotion > $product->price){ ?>
                            <span class="c-product-square__oldprice"><?= number_format($product->promotion) ?><sup>đ</sup></span>
                            <?php } ?>
                          </div>
                          <div class="c-product-square__row">
                            <span class="c-star is-<?= $product->rating ?>">
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                            </span>
                            <span class="c-product-square__view"><i class="fa fa-eye"></i><?= $product->view ?></span>
                          </div>
                          <div class="c-product-square__btn"><a href="<?= $product->createUrl() ?>">Mua ngay</a></div>
                        </div>
                      </div>
                    </div>
                  </li>
                  <?php } ?>
                </ul>
              </div><!-- c-home-product -->
            </div><!-- c-home-box -->
            <div class="c-more"><a class="btn btn-primary" href="/tim-kiem">Xem thêm</a></div>
          </div><!-- c-tabs__pane -->
        </div><!-- c-tabs__content -->
      </div><!-- c-tabs -->
    </div><!-- c-box__content -->
  </div><!-- c-box -->
</div><!-- container -->